### ISSUE TITLE
"stream processing" the incoming request

### ISSUE THREAD

**Issue by igrigorik** [FRiCKLE/ngx_zeromq#1]
@PiotrSikora: great stuff. I see you're playing with the Push/Pull sockets also.. 

Q: Does nginx allow access to the incoming stream? For example, "parsed headers", "parsed body chunk", etc, or do you have to wait until the entire request completes before you have access to it?

**Comment by PiotrSikora** [comment]
Nope, incoming request is fully buffered. This is something that will be eventually changed in order to support websockets, but we'll have to wait for nginx-2.0 for that.

Regarding sockets: I've been playing with ZMQ_SUB as well ;) The idea is to have full ZeroMQ support with sample upstream module (mongrel2 drop-in replacement) by the end of the week.

**Comment by igrigorik** [comment]
Nice. In which case, I'll have to wait for that and plugin goliath in the back as a proof of concept. :-)

Re: nginx 2.0, makes sense. There is also rumors of SPDY support, which will obviously need the same semantics.

**Comment by PiotrSikora** [comment]
Rumors are no longer rumors when they are officially confirmed ;)

Just wondering, what's the use case that would benefit from streamed incoming request?

**Comment by igrigorik** [comment]
For plain old HTTP it may be a limited use case.. consider someone streaming a large file upload, which you don't want to buffer. Ex: stream data directly to S3. 

But, for protocols like SPDY, with multiple interleaved streams and priorities it becomes a must have. SPDY > HTTP proxies work in theory, but at a big cost.

**Comment by PiotrSikora** [comment]
Large uploads _are_ the exact reason why you _want_ to buffer. With buffering, if one upstream server dies, connection get interrupted or something else breaks then you can always re-send incoming request (with that super-important upload!) to another upstream, without buffering you're busted.

SPDY is totally different story, but webservers must be rewritten from scratch (i.e. nginx-2.0) with that design in mind, otherwise you're asking for troubles and/or inferior experience.

**Comment by igrigorik** [comment]
Re, uploads: it's not a black and white scenario. If I'm uploading a 600mb video file to youtube, do you think the web frontend should buffer all of that in memory before dispatching it to the backend? Of course not.. there are, admittedly more involved, but better ways to recover and restart your uploads.

**Comment by PiotrSikora** [comment]
Not in memory, on disk. Don't get me wrong, I totally agree with you that buffering of incoming requests isn't ideal and often unwanted, but you'll have hard time convincing me that there are better ways to do request recovery.

**Comment by igrigorik** [comment]
I don't think it's a matter of convincing.. it's application level logic, which will vary from use case to use case :-)

Ex: http://code.google.com/apis/youtube/2.0/developers_guide_protocol_resumable_uploads.html#Completing_Resumable_Upload_Process

**Comment by PiotrSikora** [comment]
That really depends on the point of view.

From application developer perspective, this is indeed viable solution for _this_ use case, but it isn't generic enough (what if regular request is lost between fronted and dying backend? There is no file to resume) and it occupies backend for the whole time of request (although this isn't big problem anymore).

From hosting provider perspective, this is simply no-go, because it doesn't fix the problem for everyone on the platform.

In my books, it doesn't even come close to being better than buffering, YMMV ;)

**Comment by igrigorik** [comment]
:-) .. I guess I'll be waiting for nginx 2.0!
